#!/usr/bin/env python3

import sys

def read_file(filename):
    try:
        with open(filename, 'r') as file:
            return file.readlines()
    except FileNotFoundError:
        return ['File not found!']

def main():
    filename = 'text.txt'
    
    content = read_file(filename)
    
    if content == ['File not found!']:
        print('File not found!')
    else:
        print(''.join(content))
    
    print(f"Number of lines: {len(content)}")

if __name__ == '__main__':
    main()
